//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomsAndFurniture.Web.Queries.RoomQueries.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoomQueriesSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomQueriesSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomsAndFurniture.Web.Queries.RoomQueries.Sql.RoomQueriesSql", typeof(RoomQueriesSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Room (CreateDate, Name) values (@CreateDate, @Name);
        ///select last_insert_rowid();.
        /// </summary>
        internal static string CreateRoomQuery {
            get {
                return ResourceManager.GetString("CreateRoomQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Room
        ///    where
        ///        Name = @Name and
        ///        @Date between CreateDate and coalesce(RemoveDate, &apos;9999-12-31&apos;).
        /// </summary>
        internal static string GetRoomByNameAndDateCriterionQuery {
            get {
                return ResourceManager.GetString("GetRoomByNameAndDateCriterionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Room where Name in @Names.
        /// </summary>
        internal static string GetRoomsByNamesQuery {
            get {
                return ResourceManager.GetString("GetRoomsByNamesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 1
        ///    from Room
        ///    where
        ///        Name = @Name and
        ///        @Date between CreateDate and coalesce(RemoveDate, &apos;9999-12-31&apos;)
        ///    limit 1.
        /// </summary>
        internal static string IsRoomExistsQuery {
            get {
                return ResourceManager.GetString("IsRoomExistsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Room (CreateDate, Name) values (@CreateDate, @Name);
        ///select last_insert_rowid();.
        /// </summary>
        internal static string RemoveRoomQuery {
            get {
                return ResourceManager.GetString("RemoveRoomQuery", resourceCulture);
            }
        }
    }
}
