//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomsAndFurniture.Web.Queries.FurnitureQueries.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FurnitureQueriesSql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FurnitureQueriesSql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomsAndFurniture.Web.Queries.FurnitureQueries.Sql.FurnitureQueriesSql", typeof(FurnitureQueriesSql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Furniture (Date, Type, Count, RoomId) values (@Date, @Type, @Count, @RoomId);.
        /// </summary>
        internal static string CreateFurnitureItemsQuery {
            get {
                return ResourceManager.GetString("CreateFurnitureItemsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin transaction;
        ///    create temp table _difference(Value integer);
        ///    create temp table _createdFurnitureId(Value integer);
        ///
        ///    insert into _difference(Value)
        ///        select coalesce(@Count - Count, @Count)
        ///            from Furniture
        ///            where
        ///                Date &lt;= @Date and
        ///                Type = @Type and
        ///                RoomId = @RoomId
        ///            group by RoomId, Type
        ///            having max(Date) &lt;= @Date
        ///            limit 1;
        ///
        ///    insert into Furniture (Date, Type, Count, R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateFurnitureQuery {
            get {
                return ResourceManager.GetString("CreateFurnitureQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select f.*
        ///    from Furniture as f
        ///    inner join FurnitureLocation as fl on f.Id = fl.FurnitureId
        ///    where
        ///        f.CreateDate &lt;= @Date and (
        ///            f.RemoveDate is null or
        ///            f.RemoveDate &gt; @Date
        ///        ) and
        ///        fl.RoomId = @RoomId and
        ///        f.Type = @Type and (
        ///            fl.Date = @Date or (
        ///                fl.Date &lt; @Date and
        ///                fl.Id not in (
        ///                    select fl2.Id from FurnitureLocation as fl2
        ///                        where
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetFurnitureByTypeAndDateAndRoomIdQuery {
            get {
                return ResourceManager.GetString("GetFurnitureByTypeAndDateAndRoomIdQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select f.CreateDate as Date, f.Type, count(f.Id) as Count, fl.RoomId
        ///    from Furniture as f
        ///    inner join FurnitureLocation as fl on f.Id = fl.FurnitureId
        ///    where
        ///        f.CreateDate &lt;= @Date and (
        ///            f.RemoveDate is null or
        ///            f.RemoveDate &gt; @Date
        ///        ) and
        ///        fl.RoomId in @RoomsIds
        ///    group by fl.RoomId, f.Type;.
        /// </summary>
        internal static string GetFurnitureItemsByRoomsIdsAndDateQuery {
            get {
                return ResourceManager.GetString("GetFurnitureItemsByRoomsIdsAndDateQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin transaction;
        ///    create temp table _difference(Value integer);
        ///
        ///    insert into _difference(Value) select @Count - Count from Furniture where Id = @Id;
        ///
        ///    update Furniture set Count = @Count where Id = @Id;
        ///
        ///    update Furniture
        ///        set Count = Count + (select Value from _difference)
        ///        where 
        ///            Type = @Type and
        ///            Date &gt; @Date and
        ///            RoomId = @RoomId;
        ///
        ///    drop table _difference;
        ///end transaction;.
        /// </summary>
        internal static string UpdateFurnitureQuery {
            get {
                return ResourceManager.GetString("UpdateFurnitureQuery", resourceCulture);
            }
        }
    }
}
